### ISSUE TITLE
GoogleJsonResponseException: 404 Not Found

### ISSUE THREAD

**Issue by janprill** [googlearchive/gplus-domains-quickstart-java#3]
After following the instructions step-by-step the the app is issuing the following error:

msp-hh-mbjp:gplus-domains-quickstart-java jan.prill$ java -classpath "bin:lib/*" com.google.plus.samples.quickstart.domains.DomainDelegation
Authenticate the domain for janprill@<xxxx>
Inserting activity
Exception in thread "main" com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
Not Found
    at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1045)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
    at com.google.plus.samples.quickstart.domains.DomainDelegation.main(DomainDelegation.java:145)

A google search turns up quite some people experiencing the same. Unfortunately answers on their questions are to no avail.

Cheers, Jan

**Comment by alexatl43** [comment]
Hi, did you find a solution to this?

Best
Alex

**Comment by joannasmith** [comment]
I am unable to reproduce this error.  I tried a clean build of the app following the instructions at https://developers.google.com/+/domains/quickstart/java. Did you make any additional modifications? What is the email address you are trying to act on behalf of? Is it a Google Apps domain user?

**Comment by AlvarDev** [comment]
Hi, I have the same error and I followed the instructions step by step and the email is a Google Apps domain,  this is the message: 

Authenticate the domain for alvaro@
Sep 05, 2014 12:42:49 PM com.google.api.client.googleapis.services.AbstractGoogleClient <init>
WARNING: Application name is not set. Call Builder#setApplicationName.
Inserting activity
Exception in thread "main" com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
Not Found
    at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1045)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
    at com.google.plus.samples.quickstart.domains.DomainDelegation.main(DomainDelegation.java:148)

greetings!, Alvaro

**Comment by sivapraka** [comment]
I am also facing the same issues.

**Comment by genijmath** [comment]
I had this issue.
My solution was to update the libraries:

    <dependencies>
        <dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
            <version>1.23.0</version>
        </dependency>

        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-plusDomains</artifactId>
            <version>v1-rev449-1.23.0</version>
        </dependency>

        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client-jackson</artifactId>
            <version>1.23.0</version>
        </dependency>
    </dependencies>
